let users = [
  {
    id: '5FR8BZZxpcFJninLLATd',
    name: 'John Doe',
    email: 'john.doe@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'dLjMU922Al1mMvOa6ydl',
    name: 'Admin admin',
    email: 'admin@gmail.com',
    password: '123456',
    role: 'admin',
    isActive: true,
  },
  {
    id: '6aeMwo25MipGqwdDOFoE',
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: '7FVSkARRpFT0KqTu4iDO',
    name: 'Bob Smith',
    email: 'bob.smith@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: '7PWT9zeJu0BxAH9Gs2gn',
    name: 'Charlie Brown',
    email: 'charlie.brown@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: '7l0Y98CnzhtYSgOPK5IT',
    name: 'Grace Taylor',
    email: 'grace.taylor@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: '8cE2WxrX8jVfPiMCM3KE',
    name: 'Daniel Clark',
    email: 'daniel.clark@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'BWVY1Zai6ttqlydCsvAa',
    name: 'Charlie Brown',
    email: 'charlie.brown@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'FdEv1JHbtHkUS58ThoDP',
    name: 'Alice Johnson',
    email: 'alice.johnson@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'N6kb9rVrZVCKBwOxstvs',
    name: 'Olivia Jones',
    email: 'olivia.jones@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'OPBO9aNXuUinDS5vMpK2',
    name: 'Bob Smith',
    email: 'bob.smith@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'OgRLhRWBbBGt197mawiG',
    name: 'Emma Williams',
    email: 'emma.williams@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'QasNtSLJXcw9EbNllumi',
    name: 'Olivia Jones',
    email: 'olivia.jones@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'QwqUx3nWxODOE4MpAtar',
    name: 'Emma Williams',
    email: 'emma.williams@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'SRlaNQzl8wq4ROyQdiLI',
    name: 'John Doe',
    email: 'john.doe@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'aEalcEJRKb8vSYTEK9Hb',
    name: 'Daniel Clark',
    email: 'daniel.clark@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'bJbqoxnIAnxFoMLwxCQP',
    name: 'John Doe',
    email: 'john.doe@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'czNavzNT3j5kMIpdskun',
    name: 'Grace Taylor',
    email: 'grace.taylor@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'eXtazqHLt0xwfyCcbf11',
    name: 'David Miller',
    email: 'david.miller@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'iTL9BbBM9MOdsdJCHvUr',
    name: 'Sophie Johnson',
    email: 'sophie.johnson@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'sNg9Uitwx7PxZiYrRQ8e',
    name: 'David Miller',
    email: 'david.miller@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
  {
    id: 'tapjpkzb08al6OMcsCdR',
    name: 'Sophie Johnson',
    email: 'sophie.johnson@example.com',
    password: 'hashed password',
    role: 'user',
    isActive: true,
  },
]

export default { users }
